### ISSUE TITLE
silent moderation

### ISSUE THREAD

**Issue by KamiiQ** [netherfoam/MaxBans-4.0#14]
Why there is silent permission but no [-s] option in banning, kicking etc.?

**Comment by netherfoam** [comment]
There should be. Just use -s in the command anywhere and it should only
inform you, the target, and any moderators

Eg /ban merlin -s No wizards allowed

**Comment by netherfoam** [comment]
Is this okay now?

**Comment by KamiiQ** [comment]
Nope bro. Its not displaying _[Silent]_ like old maxbans.

Ps. if i have problems with connecting to MySql using jdbc i must create new issue?

**Comment by KamiiQ** [comment]
Ps. commands not working on 1.12 - ABSOLUTLY. (displaying messages but not kicking etc...)

**Comment by netherfoam** [comment]
Ahh right I understand what you're after.

The messages *are* silent (only you, and anyone targeted by the command are invovled) but there's no _[Silent]_ prefix to the messages. I'll add a ticket to add that for v1.6

---

If you're using v1.2 or less, I'd suggest updating to the latest version. There've been a number of small things I've fixed in MySQL connectivity if you read the change log: https://www.spigotmc.org/resources/maxbans-plus.41392/updates

**Comment by netherfoam** [comment]
Regarding the `[Silent]` tag, I've made a custom version of the plugin [here](http://maxgamer.org/plugins/maxbans-plus-1.6-SNAPSHOT.jar) if you'd like to download it.

This adds support for messages.yml to contain:
```
silent:
    prefix: "&a&o[Silent]&r&r "
    suffix: ""
```

Which will make your silent commands appear like:
![Screenshot.png](http://maxgamer.org/screenshot/gnome-screenshot.M1liXw.png)

**Comment by netherfoam** [comment]
I'll be releasing this version sometime in the future to spigot :)
