### ISSUE TITLE
Implementations to the MySQL-table?

### ISSUE THREAD

**Issue by roopekoo** [netherfoam/MaxBans-4.0#20]
Hi,
To my mind, bans section in the MySQL table is messy. I'd like it so there are simply: banned user, user/console who created the ban (not in hexadecimal), starting and ending date for the ban and the reason for the ban.
Now there are "ban_id", "source_id", "created", "expires_at", "revoked_at", "revoker_id" and "reason".
It is annoying to check eg. the ban id from another tab from the database to see further information about the ban. Could you @netherfoam make the table cleaner and easier to view?

Also, the expiration of bans or warnings doesn't vanish from the table when it is expired(After today's date is greater than expiry date, the whole column disappears). I'd like it so when I check the table of bans I see only the banned players, not some time ago banned but released. An alternative to this might be a history table for simple tabs like "name" and how many times the user has been banned.

**Comment by netherfoam** [comment]
So, I'm happy to throw in some explanations but I've also got a solution for you!

---

The reasons are:
* **Banner** is the UUID of the banner. For MySQL, UUID's are stored as binary(16) -- and your database client is formatting it as hex for you. It can't be a name -- If the admin who bans the user changes their name, it'll no longer be accurate
* **User** for the same reasons
* **Expired bans** don't vanish so that there's the _/history_ command (which, I've been a bit inactive, I don't think I've fully implemented properly yet)

---

So! This is a relational database and the data is very easily manipulated to do exactly what you want with  [Views](https://www.w3schools.com/sql/sql_view.asp) -- They let you predefine a query against your database.

So, assuming you're running with MySQL:
```sql
CREATE VIEW Nice_Bans AS
SELECT u.name as source_name, v.name as user_name, b.*
FROM Ban b
JOIN Users u ON u.id = b.source_id
JOIN Users v ON v.id = b.user_id
WHERE b.expires_at >= now();
```
* Disclaimer, I haven't tested that, but you get the general idea

And then do:
```sql
SELECT * FROM Nice_Bans
```

And you'll get everyhting nicely formatted for you!

**Comment by roopekoo** [comment]
Okay, I will try that one out :)

**Comment by netherfoam** [comment]
I'm hoping the silence means this was resolved? :smile:

**Comment by roopekoo** [comment]
Well, no. I ran into some issues trying to do those commands. Also, I haven't got any spare time trying to somehow resolve the problem.

**Comment by roopekoo** [comment]
After a long fighting against this code, I got this far:
```
CREATE VIEW nice_bans AS
SELECT
    ban.id,
    created,
    expires_at,
    reason,
    name
FROM
    ban,
    users
WHERE
    ban.id = users.id;
```
That creates a correct view and a heading but the whole view table is empty. And also does this view have also only banned users (it excludes all non-banned users from the list)?
In addition, your code returned: 
> #1054 - Unknown column 'b.user_id' in 'on clause'
Could you investigate this issue? I have not got anything to do with this. I haven't been able to figure it by myself because I don't know SQL commands well.

**Comment by netherfoam** [comment]
Sorry, perhaps try this:
```sql
CREATE VIEW nice_bans AS
SELECT u.name as source_name, v.name as user_name, b.*
FROM Ban b
JOIN Users_Ban ub ON ub.ban_id = b.id
JOIN Users u ON u.id = ub.user_id
JOIN Users_Ban vb ON vb.ban_id = b.id
JOIN Users v ON v.id = vb.user_id
WHERE b.expires_at >= now()
```

**Comment by roopekoo** [comment]
That works! Thank you!
