### ISSUE TITLE
No Permission! {Im Opped}

### ISSUE THREAD

**Issue by DarkPotato23** [netherfoam/MaxBans-4.0#24]
i run /tempban [Player] [time] -s and it says back to me in chat
"You dont have permission"
I have the permission node '*' for me in my permissions file! and im Opped on my server
this is a issue can you tell me if im missing anything that would be great! Thanks

**Comment by DarkPotato23** [comment]
I just gave myself the permission node maxbans.ban and i still dont have permission for banning players!

**Comment by DarkPotato23** [comment]
if you could DM me on Discord it would be greatly appriciated!
Dark_Potato23#4851

**Comment by DarkPotato23** [comment]
Every command works even /mbreload
The only commands that dont work on the server are mute, kick, ban, and warn
I dont think lockdown works either

**Comment by netherfoam** [comment]
I've added you on Discord (User: `genikus`) but there afew a few things I've noticed immediately:

### Wrong Version
You're running the old version of `MaxBans` from Bukkit, which is forked and maintained by Fabio12. This is the source repository for `MaxBans Plus` - A rewrite I'm doing and have released to only the Spigot community for testing. I can tell because this new rewrite doesn't have `mbreload` implemented yet.

### Interference from another Plugin
The literal string `You dont have permission` doesn't appear in my source code for either repositories I don't think. So perhaps another plugin is receiving the command. To help with this, I aliased all of my MaxBans commands with an optional `mb` prefix. Eg `mbkick`, `mbban`, mbunmute`. So, try use `/mbtempban <Player> [Time] [-s] [Message]` instead, and it'll probably work fine. 

If the workaround makes a difference, then it's confirmed that another plugin is overriding my commands! If that's the problem, I wrote a very old page on solving it here: https://dev.bukkit.org/projects/maxbans/pages/common-issues

I think maybe bukkit uses a `commands.yml` file instead of a `bukkit.yml` file now though, I'm not sure

**Comment by DarkPotato23** [comment]
I got it working turns out i have Lite Bans installed and i removed my permissions for that plugin causing mixes, Thanks for the help and i will download the newest version 🗡
